"""Add user notification preferences

Revision ID: fe12cdda6ce3
Revises: 
Create Date: 2026-06-14 06:31:48.907365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe12cdda6ce3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pref_email_notifications', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('pref_inapp_notifications', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('pref_booking_reminders', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pref_booking_reminders')
    op.drop_column('users', 'pref_inapp_notifications')
    op.drop_column('users', 'pref_email_notifications')
    # ### end Alembic commands ###
